# Vault Keys Secret
# IMPORTANT: This contains sensitive credentials - for dev/lab use only
# In production, use a secure secret management solution
apiVersion: v1
kind: Secret
metadata:
  name: vault-keys
  namespace: vault
type: Opaque
stringData:
  unseal_key: "3k6WXVbFLuGKNNIa45qmjsHHouaH6pCGnVZi+dr0tl0="
  root_token: "hvs.1MmdQ3PhmwE9SnX309vLwEj2"
