apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# This directory contains integration test documentation
# No Kubernetes resources are applied here

commonLabels:
  app: tfe-integration-test
